CREATE TABLE [dbo].[EmailTemplate]
(
	[Id] BIGINT NOT NULL IDENTITY CONSTRAINT [PK_EmailTemplate] PRIMARY KEY CLUSTERED ([Id] ASC),
	[Name] NVARCHAR(255) NOT NULL,
	[Content] NVARCHAR(MAX) NOT NULL
)
